Q:

Problem when launching nav2_bringup with your own param file

I am encountering issues when attempting to pass my own parameter file while launching nav2_bringup. It appears that none of my configurations take effect. The command ros2 launch nav2_bringup tb3_simulation_launch.py params_file:=my_nav2_params.yaml is not working for me in Rolling.
I checked the launch.py script, and it seems that params_file is being taken into account. I’m unsure of what might be happening. Do you have any ideas?

A:

I just updated nav2, and now it’s working. I’m not sure if it’s because of the update or if I was doing something wrong.

