Q:

'volume' error using sound_play

I can't find a way a make sound_play work. I've been searching for days already, but I can't find a fix to this error. Have any of you ever experienced this error?
$ rosrun sound_play say.py 'Hello again'

Saying: Hello again
Voice: voice_kal_diphone Traceback (most recent call last):
File: "/opt/ros/indigo/lib/sound_play/say.py",
line 79, in 
print 'Volume: %s' % volume NameError: name 'volume' is not
defined

Originally posted by the8Bitts on ROS Answers with karma: 1 on 2016-02-02
Post score: 0

A:

This is a bug in sound_play. Please report it on the issue tracker.
UPDATE
The bug was reported here: https://github.com/ros-drivers/audio_common/issues/72 and is fixed in the most recent release of sound_play, which has not yet made it to the public apt repository.
Until then, if this issue is a problem, please use audio_common from source by checking out the audio_common repository into your catkin workspace.
DO NOT modify the files in /opt/ros ; they are managed by the package manager and your changes may be overwritten at any time.

Originally posted by ahendrix with karma: 47576 on 2016-02-03
This answer was ACCEPTED on the original site
Post score: 1

