Q:

No module named gps_goal

Cloned gps_goal into my catkin workspace, catkin_make didn't return any error. When running the following command, it returns an importerror
 yuxiang@yuxiang:~/catkin_ws2$ roslaunch gps_goal gps_goal.launch
... logging to /home/yuxiang/.ros/log/434b3910-0c46-11ed-881b-3f02c6700c9f/roslaunch-yuxiang-445884.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://yuxiang:38821/

SUMMARY
========

PARAMETERS
 * /gps_goal/frame_id: map
 * /rosdistro: noetic
 * /rosversion: 1.15.14

NODES
  /
    gps_goal (gps_goal/gps_goal)

auto-starting new master
process[master]: started with pid [445899]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 434b3910-0c46-11ed-881b-3f02c6700c9f
process[rosout-1]: started with pid [445916]
started core service [/rosout]
process[gps_goal-2]: started with pid [445919]
Traceback (most recent call last):
  File "/home/yuxiang/catkin_ws2/src/gps_goal/nodes/gps_goal", line 3, in <module>
    from gps_goal import gps_goal
ImportError: No module named gps_goal
[gps_goal-2] process has died [pid 445919, exit code 1, cmd /home/yuxiang/catkin_ws2/src/gps_goal/nodes/gps_goal gps_goal_pose:=gps_goal_pose gps_goal_fix:=gps_goal_fix local_xy_origin:=local_xy_origin __name:=gps_goal __log:=/home/yuxiang/.ros/log/434b3910-0c46-11ed-881b-3f02c6700c9f/gps_goal-2.log].
log file: /home/yuxiang/.ros/log/434b3910-0c46-11ed-881b-3f02c6700c9f/gps_goal-2*.log
^C[rosout-1] killing on exit

Originally posted by noname on ROS Answers with karma: 15 on 2022-07-25
Post score: 0

A:

Did you source (e.g. source devel/setup.bash in the catkin_ws folder) the workspace after catkin_make?

Originally posted by ljaniec with karma: 3064 on 2022-07-26
This answer was ACCEPTED on the original site
Post score: 1

Original comments
Comment by noname on 2022-07-26:
Yes I did, unfortunately it still does not work
Comment by ljaniec on 2022-07-27:
Can you link this package so we can check how it works? Then I could check if it builds in my workspace. Is it this one? It is for ROS Kinetic, there is no ros-noetic-gps-goal binary package as I checked. Remember that ROS Kinetic uses Python 2.7, not Python 3. You can try to rebuild it with deleting install, log, build folders, then source devel/setup.bash and check again. You can try to use not the launch file, but the CLI with python gps_goal.py
Comment by noname on 2022-07-29:
I noticed that the package has not been updated for a few years. Thanks for the help I will try python gps_goal.py
Comment by noname on 2022-08-13:
It works, thank you boss
Comment by ljaniec on 2022-08-14:
If it worked, please accept it as an answer :)
Comment by noname on 2022-08-14:
I thought I already did?
Comment by ljaniec on 2022-08-15:
You have a second button under the <1> with text "mark this answer as correct` - I thought about this one

